trigger:
  - main  # Runs the pipeline when you push to the main branch

pool:
  vmImage: 'ubuntu-latest'  # You can use windows-latest if needed

variables:
  buildConfiguration: 'Release'

steps:
- name: Checkout code
  uses: actions/checkout@v3

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'  # Use your .NET version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- name: Restore Dependencies
  run: dotnet restore

- name: Build the Solution
  run: dotnet build --configuration $(buildConfiguration) --no-restore

- name: Run Unit Tests
  run: dotnet test --configuration $(buildConfiguration) --no-build

- name: Publish Blazor App
  run: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Your-Azure-Service-Connection'
    appName: 'your-blazor-app'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
